apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

namespace: cloudguard

resources:
- namespace.yaml
- configmap.yaml
- secret.yaml
- postgres.yaml
- redis.yaml
- deployment.yaml
- service.yaml
- ingress.yaml
- hpa.yaml
- pdb.yaml
- networkpolicy.yaml
- rbac.yaml

commonLabels:
  app.kubernetes.io/name: cloudguard-anomaly
  app.kubernetes.io/version: "3.0"
  app.kubernetes.io/component: security-scanner
  app.kubernetes.io/managed-by: kustomize

images:
- name: ghcr.io/NAMESPACE/cloudguard-anomaly
  newTag: latest
