apiVersion: policy/v1
kind: PodDisruptionBudget
metadata:
  name: cloudguard-anomaly
  namespace: cloudguard
  labels:
    app: cloudguard-anomaly
spec:
  minAvailable: 2
  selector:
    matchLabels:
      app: cloudguard-anomaly
